import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from './index.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <Link className={styles.link} href="/graph">
          Test
        </Link>
        <Link className={styles.link} href="/graph">
          K3
        </Link>
      </div>
    </>
  );
}
